# This file was automagically generated by mbed.org. For more information, 
# see http://mbed.org/handbook/Exporting-to-GCC-ARM-Embedded

###############################################################################
# Boiler-plate

# cross-platform directory manipulation
ifeq ($(shell echo $$OS),$$OS)
    MAKEDIR = if not exist "$(1)" mkdir "$(1)"
    RM = rmdir /S /Q "$(1)"
else
    MAKEDIR = '$(SHELL)' -c "mkdir -p \"$(1)\""
    RM = '$(SHELL)' -c "rm -rf \"$(1)\""
endif

OBJDIR := BUILD
# Move to the build directory
ifeq (,$(filter $(OBJDIR),$(notdir $(CURDIR))))
.SUFFIXES:
mkfile_path := $(abspath $(lastword $(MAKEFILE_LIST)))
MAKETARGET = '$(MAKE)' --no-print-directory -C $(OBJDIR) -f '$(mkfile_path)' \
		'SRCDIR=$(CURDIR)' $(MAKECMDGOALS)
.PHONY: $(OBJDIR) clean
all:
	+@$(call MAKEDIR,$(OBJDIR))
	+@$(MAKETARGET)
$(OBJDIR): all
Makefile : ;
% :: $(OBJDIR) ; :
clean :
	$(call RM,$(OBJDIR))

else

# trick rules into thinking we are in the root, when we are in the bulid dir
VPATH = ..

# Boiler-plate
###############################################################################
# Project settings

PROJECT := mbed_EFM32HG_STK3400


# Project settings
###############################################################################
# Objects and Paths

OBJECTS += main.o

 SYS_OBJECTS += TARGET_EFM32HG_STK3400/TOOLCHAIN_GCC_ARM/analogin_api.o
 SYS_OBJECTS += TARGET_EFM32HG_STK3400/TOOLCHAIN_GCC_ARM/analogout_api.o
 SYS_OBJECTS += TARGET_EFM32HG_STK3400/TOOLCHAIN_GCC_ARM/cmsis_nvic.o
 SYS_OBJECTS += TARGET_EFM32HG_STK3400/TOOLCHAIN_GCC_ARM/dma_api.o
 SYS_OBJECTS += TARGET_EFM32HG_STK3400/TOOLCHAIN_GCC_ARM/em_acmp.o
 SYS_OBJECTS += TARGET_EFM32HG_STK3400/TOOLCHAIN_GCC_ARM/em_adc.o
 SYS_OBJECTS += TARGET_EFM32HG_STK3400/TOOLCHAIN_GCC_ARM/em_aes.o
 SYS_OBJECTS += TARGET_EFM32HG_STK3400/TOOLCHAIN_GCC_ARM/em_assert.o
 SYS_OBJECTS += TARGET_EFM32HG_STK3400/TOOLCHAIN_GCC_ARM/em_burtc.o
 SYS_OBJECTS += TARGET_EFM32HG_STK3400/TOOLCHAIN_GCC_ARM/em_cmu.o
 SYS_OBJECTS += TARGET_EFM32HG_STK3400/TOOLCHAIN_GCC_ARM/em_core.o
 SYS_OBJECTS += TARGET_EFM32HG_STK3400/TOOLCHAIN_GCC_ARM/em_cryotimer.o
 SYS_OBJECTS += TARGET_EFM32HG_STK3400/TOOLCHAIN_GCC_ARM/em_crypto.o
 SYS_OBJECTS += TARGET_EFM32HG_STK3400/TOOLCHAIN_GCC_ARM/em_dac.o
 SYS_OBJECTS += TARGET_EFM32HG_STK3400/TOOLCHAIN_GCC_ARM/em_dbg.o
 SYS_OBJECTS += TARGET_EFM32HG_STK3400/TOOLCHAIN_GCC_ARM/em_dma.o
 SYS_OBJECTS += TARGET_EFM32HG_STK3400/TOOLCHAIN_GCC_ARM/em_ebi.o
 SYS_OBJECTS += TARGET_EFM32HG_STK3400/TOOLCHAIN_GCC_ARM/em_emu.o
 SYS_OBJECTS += TARGET_EFM32HG_STK3400/TOOLCHAIN_GCC_ARM/em_gpcrc.o
 SYS_OBJECTS += TARGET_EFM32HG_STK3400/TOOLCHAIN_GCC_ARM/em_gpio.o
 SYS_OBJECTS += TARGET_EFM32HG_STK3400/TOOLCHAIN_GCC_ARM/em_i2c.o
 SYS_OBJECTS += TARGET_EFM32HG_STK3400/TOOLCHAIN_GCC_ARM/em_idac.o
 SYS_OBJECTS += TARGET_EFM32HG_STK3400/TOOLCHAIN_GCC_ARM/em_int.o
 SYS_OBJECTS += TARGET_EFM32HG_STK3400/TOOLCHAIN_GCC_ARM/em_lcd.o
 SYS_OBJECTS += TARGET_EFM32HG_STK3400/TOOLCHAIN_GCC_ARM/em_ldma.o
 SYS_OBJECTS += TARGET_EFM32HG_STK3400/TOOLCHAIN_GCC_ARM/em_lesense.o
 SYS_OBJECTS += TARGET_EFM32HG_STK3400/TOOLCHAIN_GCC_ARM/em_letimer.o
 SYS_OBJECTS += TARGET_EFM32HG_STK3400/TOOLCHAIN_GCC_ARM/em_leuart.o
 SYS_OBJECTS += TARGET_EFM32HG_STK3400/TOOLCHAIN_GCC_ARM/em_mpu.o
 SYS_OBJECTS += TARGET_EFM32HG_STK3400/TOOLCHAIN_GCC_ARM/em_msc.o
 SYS_OBJECTS += TARGET_EFM32HG_STK3400/TOOLCHAIN_GCC_ARM/em_opamp.o
 SYS_OBJECTS += TARGET_EFM32HG_STK3400/TOOLCHAIN_GCC_ARM/em_pcnt.o
 SYS_OBJECTS += TARGET_EFM32HG_STK3400/TOOLCHAIN_GCC_ARM/em_prs.o
 SYS_OBJECTS += TARGET_EFM32HG_STK3400/TOOLCHAIN_GCC_ARM/em_rmu.o
 SYS_OBJECTS += TARGET_EFM32HG_STK3400/TOOLCHAIN_GCC_ARM/em_rtc.o
 SYS_OBJECTS += TARGET_EFM32HG_STK3400/TOOLCHAIN_GCC_ARM/em_rtcc.o
 SYS_OBJECTS += TARGET_EFM32HG_STK3400/TOOLCHAIN_GCC_ARM/em_system.o
 SYS_OBJECTS += TARGET_EFM32HG_STK3400/TOOLCHAIN_GCC_ARM/em_timer.o
 SYS_OBJECTS += TARGET_EFM32HG_STK3400/TOOLCHAIN_GCC_ARM/em_usart.o
 SYS_OBJECTS += TARGET_EFM32HG_STK3400/TOOLCHAIN_GCC_ARM/em_vcmp.o
 SYS_OBJECTS += TARGET_EFM32HG_STK3400/TOOLCHAIN_GCC_ARM/em_wdog.o
 SYS_OBJECTS += TARGET_EFM32HG_STK3400/TOOLCHAIN_GCC_ARM/gpio_api.o
 SYS_OBJECTS += TARGET_EFM32HG_STK3400/TOOLCHAIN_GCC_ARM/gpio_irq_api.o
 SYS_OBJECTS += TARGET_EFM32HG_STK3400/TOOLCHAIN_GCC_ARM/i2c_api.o
 SYS_OBJECTS += TARGET_EFM32HG_STK3400/TOOLCHAIN_GCC_ARM/lp_ticker.o
 SYS_OBJECTS += TARGET_EFM32HG_STK3400/TOOLCHAIN_GCC_ARM/mbed_board.o
 SYS_OBJECTS += TARGET_EFM32HG_STK3400/TOOLCHAIN_GCC_ARM/mbed_overrides.o
 SYS_OBJECTS += TARGET_EFM32HG_STK3400/TOOLCHAIN_GCC_ARM/PeripheralPins.o
 SYS_OBJECTS += TARGET_EFM32HG_STK3400/TOOLCHAIN_GCC_ARM/pinmap.o
 SYS_OBJECTS += TARGET_EFM32HG_STK3400/TOOLCHAIN_GCC_ARM/pinmap_function.o
 SYS_OBJECTS += TARGET_EFM32HG_STK3400/TOOLCHAIN_GCC_ARM/port_api.o
 SYS_OBJECTS += TARGET_EFM32HG_STK3400/TOOLCHAIN_GCC_ARM/pwmout_api.o
 SYS_OBJECTS += TARGET_EFM32HG_STK3400/TOOLCHAIN_GCC_ARM/retarget.o
 SYS_OBJECTS += TARGET_EFM32HG_STK3400/TOOLCHAIN_GCC_ARM/rtc_api.o
 SYS_OBJECTS += TARGET_EFM32HG_STK3400/TOOLCHAIN_GCC_ARM/serial_api.o
 SYS_OBJECTS += TARGET_EFM32HG_STK3400/TOOLCHAIN_GCC_ARM/sleep.o
 SYS_OBJECTS += TARGET_EFM32HG_STK3400/TOOLCHAIN_GCC_ARM/spi_api.o
 SYS_OBJECTS += TARGET_EFM32HG_STK3400/TOOLCHAIN_GCC_ARM/startup_efm32hg.o
 SYS_OBJECTS += TARGET_EFM32HG_STK3400/TOOLCHAIN_GCC_ARM/system_efm32hg.o
 SYS_OBJECTS += TARGET_EFM32HG_STK3400/TOOLCHAIN_GCC_ARM/us_ticker.o

INCLUDE_PATHS += -I../
INCLUDE_PATHS += -I../.
INCLUDE_PATHS += -I../TARGET_EFM32HG_STK3400
INCLUDE_PATHS += -I../TARGET_EFM32HG_STK3400/TARGET_Silicon_Labs
INCLUDE_PATHS += -I../TARGET_EFM32HG_STK3400/TARGET_Silicon_Labs/TARGET_EFM32
INCLUDE_PATHS += -I../TARGET_EFM32HG_STK3400/TARGET_Silicon_Labs/TARGET_EFM32/TARGET_EFM32HG
INCLUDE_PATHS += -I../TARGET_EFM32HG_STK3400/TARGET_Silicon_Labs/TARGET_EFM32/TARGET_EFM32HG/TARGET_EFM32HG_STK3400
INCLUDE_PATHS += -I../TARGET_EFM32HG_STK3400/TARGET_Silicon_Labs/TARGET_EFM32/TARGET_EFM32HG/device
INCLUDE_PATHS += -I../TARGET_EFM32HG_STK3400/TARGET_Silicon_Labs/TARGET_EFM32/common
INCLUDE_PATHS += -I../TARGET_EFM32HG_STK3400/TARGET_Silicon_Labs/TARGET_EFM32/emlib
INCLUDE_PATHS += -I../TARGET_EFM32HG_STK3400/TARGET_Silicon_Labs/TARGET_EFM32/emlib/inc
INCLUDE_PATHS += -I../TARGET_EFM32HG_STK3400/TOOLCHAIN_GCC_ARM
INCLUDE_PATHS += -I../drivers
INCLUDE_PATHS += -I../hal
INCLUDE_PATHS += -I../platform

LIBRARY_PATHS := -L../TARGET_EFM32HG_STK3400/TOOLCHAIN_GCC_ARM 
LIBRARIES := -l:libmbed.a 
LINKER_SCRIPT ?= ../TARGET_EFM32HG_STK3400/TOOLCHAIN_GCC_ARM/efm32hg.ld

# Objects and Paths
###############################################################################
# Tools and Flags

AS      = 'arm-none-eabi-gcc' '-x' 'assembler-with-cpp' '-c' '-Wall' '-Wextra' '-Wno-unused-parameter' '-Wno-missing-field-initializers' '-fmessage-length=0' '-fno-exceptions' '-fno-builtin' '-ffunction-sections' '-fdata-sections' '-funsigned-char' '-MMD' '-fno-delete-null-pointer-checks' '-fomit-frame-pointer' '-O0' '-g3' '-DMBED_RTOS_SINGLE_THREAD' '-mcpu=cortex-m0plus' '-mthumb'
CC      = 'arm-none-eabi-gcc' '-std=gnu99' '-c' '-Wall' '-Wextra' '-Wno-unused-parameter' '-Wno-missing-field-initializers' '-fmessage-length=0' '-fno-exceptions' '-fno-builtin' '-ffunction-sections' '-fdata-sections' '-funsigned-char' '-MMD' '-fno-delete-null-pointer-checks' '-fomit-frame-pointer' '-O0' '-g3' '-DMBED_RTOS_SINGLE_THREAD' '-mcpu=cortex-m0plus' '-mthumb'
CPP     = 'arm-none-eabi-g++' '-std=gnu++98' '-fno-rtti' '-Wvla' '-c' '-Wall' '-Wextra' '-Wno-unused-parameter' '-Wno-missing-field-initializers' '-fmessage-length=0' '-fno-exceptions' '-fno-builtin' '-ffunction-sections' '-fdata-sections' '-funsigned-char' '-MMD' '-fno-delete-null-pointer-checks' '-fomit-frame-pointer' '-O0' '-g3' '-DMBED_RTOS_SINGLE_THREAD' '-mcpu=cortex-m0plus' '-mthumb'
LD      = 'arm-none-eabi-gcc' '-Wl,--gc-sections' '-mcpu=cortex-m0plus' '-mthumb'
ELF2BIN = 'arm-none-eabi-objcopy'


C_FLAGS += -std=gnu99
C_FLAGS += -DDEVICE_ERROR_PATTERN=1
C_FLAGS += -DDEVICE_SPI=1
C_FLAGS += -D__MBED__=1
C_FLAGS += -DDEVICE_I2CSLAVE=1
C_FLAGS += -DTARGET_LIKE_MBED
C_FLAGS += -DDEVICE_PORTINOUT=1
C_FLAGS += -D__MBED_CMSIS_RTOS_CM
C_FLAGS += -DDEVICE_LOWPOWERTIMER=1
C_FLAGS += -DDEVICE_RTC=1
C_FLAGS += -DTOOLCHAIN_object
C_FLAGS += -DDEVICE_SERIAL_ASYNCH=1
C_FLAGS += -D__CMSIS_RTOS
C_FLAGS += -DTOOLCHAIN_GCC
C_FLAGS += -DDEVICE_I2C_ASYNCH=1
C_FLAGS += -DTARGET_LIKE_CORTEX_M0
C_FLAGS += -DTARGET_DEBUG
C_FLAGS += -DTARGET_M0P
C_FLAGS += -DTARGET_UVISOR_UNSUPPORTED
C_FLAGS += -DTARGET_EFM32HG
C_FLAGS += -DTARGET_EFM32HG322F64
C_FLAGS += -DMBED_BUILD_TIMESTAMP=1491377164.26
C_FLAGS += -DDEVICE_INTERRUPTIN=1
C_FLAGS += -DTRANSACTION_QUEUE_SIZE_SPI=0
C_FLAGS += -DDEVICE_I2C=1
C_FLAGS += -DDEVICE_PORTOUT=1
C_FLAGS += -D__CORTEX_M0PLUS
C_FLAGS += -DDEVICE_STDIO_MESSAGES=1
C_FLAGS += -DDEVICE_SPI_ASYNCH=1
C_FLAGS += -DEFM32HG322F64
C_FLAGS += -DTARGET_EFM32
C_FLAGS += -DDEVICE_SERIAL=1
C_FLAGS += -DTARGET_64K
C_FLAGS += -DARM_MATH_CM0PLUS
C_FLAGS += -DDEVICE_PORTIN=1
C_FLAGS += -DDEVICE_SLEEP=1
C_FLAGS += -DTOOLCHAIN_GCC_ARM
C_FLAGS += -DTARGET_Silicon_Labs
C_FLAGS += -DDEVICE_SPISLAVE=1
C_FLAGS += -DDEVICE_ANALOGIN=1
C_FLAGS += -DDEVICE_PWMOUT=1
C_FLAGS += -DTARGET_EFM32HG_STK3400
C_FLAGS += -DTARGET_CORTEX_M
C_FLAGS += -include
C_FLAGS += mbed_config.h

CXX_FLAGS += -std=gnu++98
CXX_FLAGS += -fno-rtti
CXX_FLAGS += -Wvla
CXX_FLAGS += -DDEVICE_ERROR_PATTERN=1
CXX_FLAGS += -DDEVICE_SPI=1
CXX_FLAGS += -D__MBED__=1
CXX_FLAGS += -DDEVICE_I2CSLAVE=1
CXX_FLAGS += -DTARGET_LIKE_MBED
CXX_FLAGS += -DDEVICE_PORTINOUT=1
CXX_FLAGS += -D__MBED_CMSIS_RTOS_CM
CXX_FLAGS += -DDEVICE_LOWPOWERTIMER=1
CXX_FLAGS += -DDEVICE_RTC=1
CXX_FLAGS += -DTOOLCHAIN_object
CXX_FLAGS += -DDEVICE_SERIAL_ASYNCH=1
CXX_FLAGS += -D__CMSIS_RTOS
CXX_FLAGS += -DTOOLCHAIN_GCC
CXX_FLAGS += -DDEVICE_I2C_ASYNCH=1
CXX_FLAGS += -DTARGET_LIKE_CORTEX_M0
CXX_FLAGS += -DTARGET_DEBUG
CXX_FLAGS += -DTARGET_M0P
CXX_FLAGS += -DTARGET_UVISOR_UNSUPPORTED
CXX_FLAGS += -DTARGET_EFM32HG
CXX_FLAGS += -DTARGET_EFM32HG322F64
CXX_FLAGS += -DMBED_BUILD_TIMESTAMP=1491377164.26
CXX_FLAGS += -DDEVICE_INTERRUPTIN=1
CXX_FLAGS += -DTRANSACTION_QUEUE_SIZE_SPI=0
CXX_FLAGS += -DDEVICE_I2C=1
CXX_FLAGS += -DDEVICE_PORTOUT=1
CXX_FLAGS += -D__CORTEX_M0PLUS
CXX_FLAGS += -DDEVICE_STDIO_MESSAGES=1
CXX_FLAGS += -DDEVICE_SPI_ASYNCH=1
CXX_FLAGS += -DEFM32HG322F64
CXX_FLAGS += -DTARGET_EFM32
CXX_FLAGS += -DDEVICE_SERIAL=1
CXX_FLAGS += -DTARGET_64K
CXX_FLAGS += -DARM_MATH_CM0PLUS
CXX_FLAGS += -DDEVICE_PORTIN=1
CXX_FLAGS += -DDEVICE_SLEEP=1
CXX_FLAGS += -DTOOLCHAIN_GCC_ARM
CXX_FLAGS += -DTARGET_Silicon_Labs
CXX_FLAGS += -DDEVICE_SPISLAVE=1
CXX_FLAGS += -DDEVICE_ANALOGIN=1
CXX_FLAGS += -DDEVICE_PWMOUT=1
CXX_FLAGS += -DTARGET_EFM32HG_STK3400
CXX_FLAGS += -DTARGET_CORTEX_M
CXX_FLAGS += -include
CXX_FLAGS += mbed_config.h

ASM_FLAGS += -x
ASM_FLAGS += assembler-with-cpp
ASM_FLAGS += -DTRANSACTION_QUEUE_SIZE_SPI=0
ASM_FLAGS += -D__CORTEX_M0PLUS
ASM_FLAGS += -D__MBED_CMSIS_RTOS_CM
ASM_FLAGS += -DEFM32HG322F64
ASM_FLAGS += -D__CMSIS_RTOS
ASM_FLAGS += -DARM_MATH_CM0PLUS


LD_FLAGS :=-Wl,--gc-sections --specs=nano.specs -mcpu=cortex-m0plus -mthumb 
LD_SYS_LIBS :=-Wl,--start-group -lstdc++ -lsupc++ -lm -lc -lgcc -lnosys -Wl,--end-group

# Tools and Flags
###############################################################################
# Rules

.PHONY: all lst size


all: $(PROJECT).bin $(PROJECT).hex size


.asm.o:
	+@$(call MAKEDIR,$(dir $@))
	+@echo "Assemble: $(notdir $<)"
	@$(AS) -c $(ASM_FLAGS) $(INCLUDE_PATHS) -o $@ $<

.s.o:
	+@$(call MAKEDIR,$(dir $@))
	+@echo "Assemble: $(notdir $<)"
	@$(AS) -c $(ASM_FLAGS) $(INCLUDE_PATHS) -o $@ $<

.S.o:
	+@$(call MAKEDIR,$(dir $@))
	+@echo "Assemble: $(notdir $<)"
	@$(AS) -c $(ASM_FLAGS) $(INCLUDE_PATHS) -o $@ $<

.c.o:
	+@$(call MAKEDIR,$(dir $@))
	+@echo "Compile: $(notdir $<)"
	@$(CC) $(C_FLAGS) $(INCLUDE_PATHS) -o $@ $<

.cpp.o:
	+@$(call MAKEDIR,$(dir $@))
	+@echo "Compile: $(notdir $<)"
	@$(CPP) $(CXX_FLAGS) $(INCLUDE_PATHS) -o $@ $<


$(PROJECT).elf: $(OBJECTS) $(SYS_OBJECTS) $(LINKER_SCRIPT)
	+@echo "link: $(notdir $@)"
	@$(LD) $(LD_FLAGS) -T $(filter %.ld, $^) $(LIBRARY_PATHS) --output $@ $(filter %.o, $^) $(LIBRARIES) $(LD_SYS_LIBS)


$(PROJECT).bin: $(PROJECT).elf
	$(ELF2BIN) -O binary $< $@
	+@echo "===== bin file ready to flash: $(OBJDIR)/$@ =====" 

$(PROJECT).hex: $(PROJECT).elf
	$(ELF2BIN) -O ihex $< $@


# Rules
###############################################################################
# Dependencies

DEPS = $(OBJECTS:.o=.d) $(SYS_OBJECTS:.o=.d)
-include $(DEPS)
endif

# Dependencies
###############################################################################
